itertools and others
katyammah/tasks_from_hacker pull request #6
Opened 2022-04-14 07:46 UTC by katyammah

2022-04-18 09:27 UTC, zdrasteenastya requested changes
В целом, как с этим разберешься, можно идти к заданиям уровень middle
Но я бы предложила сделать сначала либо гугл курсы, либо джанго
Мне кажется лучше все таки начать с заданий гугла, хоть они и на англ. Если что то не понятно там будет - пиши, переведем. У тебя как вообще дела с англ?

2022-04-18 09:27 UTC, zdrasteenastya commented on list_comprehension.py
> +    print(a)
задание называется [list_comprehension.py]
это про https://habr.com/ru/post/30232/

нужно переписать в одну строку

2022-04-18 09:27 UTC, zdrasteenastya commented on set.add.py
> +print(len(countries))
тоже можно переписать в одну строку, как и выше

2022-04-22 13:47 UTC, katyammah commented on alphabet_rangoli.py
> +
здесь я подразумеваю, что все буквы алфавита записаны у меня в одной строке (letters), и в этой строке у каждой буквы есть свой порядковый номер, который потом использую в функции

2022-04-27 18:45 UTC, merged